Add files via upload
RodionovRL/java-filmorate pull request #17
Opened 2023-06-24 08:00 UTC by Panfilov50

2023-06-24 10:53 UTC, mrmaximum80 reviewed
Все хорошо )
Есть пару вопросов.

2023-06-24 10:53 UTC, mrmaximum80 commented on src/main/java/ru/yandex/practicum/filmorate/api/FilmStorage.java
>  }
Лучше поменять везде Collection на List.

2023-06-24 10:53 UTC, mrmaximum80 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    }
Здесь решили возвращать new ArrayList<>(), а не null.

2023-06-24 10:53 UTC, mrmaximum80 commented on src/main/resources/schema.sql
> +    film_id BIGINT    NOT NULL REFERENCES film (id) ON DELETE CASCADE,
Опа, не увидели мы ошибку в таблице! 
Хорошо, что ты исправил! )

2023-06-24 12:11 UTC, RodionovRL approved these changes

2023-06-24 12:11 UTC, RodionovRL commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    }
+1

2023-06-25 06:09 UTC, RodionovRL requested changes

2023-06-25 06:09 UTC, RodionovRL commented on src/main/java/ru/yandex/practicum/filmorate/api/FilmStorage.java
> -    Collection<Film> getListCommonFilms(Long userId, Long friendId);
Не совсем понятно, зачем удалять из интерфейсв Общие фильмы

2023-06-25 06:09 UTC, RodionovRL commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> -        return filmService.getListCommonFilms(userId, friendId);
Почему ты удаляешь функциональность общих фильмов?

2023-06-25 06:09 UTC, RodionovRL commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> -    }
Тот же вопрос про Общие фильмы

2023-06-25 06:09 UTC, RodionovRL commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> -
Общие фильмы

2023-06-25 08:32 UTC, Panfilov50 commented
Отредактировал все проблемы с целостностью.

2023-06-25 08:53 UTC, mrmaximum80 approved these changes

2023-06-25 08:54 UTC, RodionovRL approved these changes

2023-06-25 09:31 UTC, merged