Отзывы, первый комит
RodionovRL/java-filmorate pull request #8
Opened 2023-06-21 10:35 UTC by Rorshix

2023-06-21 17:03 UTC, RodionovRL requested changes
Работа проделана серьёзная. Есть замечания. Их можно обсудить:
1. Язык логов.
2. Использование отдельных методов для проверки наличия записи.
Необходимо проапдейтить локальный репозиторий и разрешить конфликты (если будут) в БД.
Необходимо сделать так, чтобы все имеющиеся тесты в приложении и тесты постмана проходили успешно.

2023-06-21 17:03 UTC, RodionovRL commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +    public boolean isUserExists(Long id) {
Не понял зачем нужен этот метод. Он дублирует метод checkUserIsExist.

2023-06-21 17:03 UTC, RodionovRL commented on pom.xml
> +		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
Не понял манёвра.

2023-06-21 17:03 UTC, RodionovRL commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +	private final EventStorage eventStorage;
Не нужен ли здесь @Autowired?

2023-06-21 17:03 UTC, RodionovRL commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +				new ReviewNotFoundException(String.format("Attempt to get review with absent id = %d",
У нас везде на русском комментарии. Полагаю, что нужно придерживаться единства стиля.

2023-06-21 17:03 UTC, RodionovRL commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +			// ignore
это что?

2023-06-21 17:03 UTC, RodionovRL commented on src/main/java/ru/yandex/practicum/filmorate/model/Event.java
> +		public Event build() {
Зачем этот медод?

2023-06-21 17:03 UTC, RodionovRL commented on pom.xml
> +</project>
А здесь что?

2023-06-21 17:03 UTC, RodionovRL commented on src/main/java/ru/yandex/practicum/filmorate/dao/EventDbStorage.java
> +	public Event mapRow(ResultSet rs, int rowNum) throws SQLException {
Не совсем понял, где используется этот метод.

2023-06-21 17:03 UTC, RodionovRL commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +    public boolean isFilmExists(Long id) {
Вообще я думаю, что подобные методы лишние. Есть метод getFilmById. Он прекрасно справляется с верификацией наличия фильма. И в текущий момент работает именно так.

2023-06-21 17:03 UTC, RodionovRL commented on src/main/java/ru/yandex/practicum/filmorate/api/ReviewStorage.java
> +	boolean isReviewExists(Long id);
Аналогично. Можно просто достать ревью из базы по id и сразу станет понятно есть такое или нет.
Можно совместно командой обсудить.

2023-06-21 17:03 UTC, RodionovRL commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +		log.info("Request to get reviews, filmId = {}, count = {}", filmId == null ? "all" : filmId, count);
Думаю, что язык нужно использовать русский, потому как изначально использовался он.

2023-06-21 17:03 UTC, RodionovRL commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +	@NotNull
Нужно добавить сообщения к аннотациям.

2023-06-22 07:04 UTC, Rorshix commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +    public boolean isUserExists(Long id) {
да я пытался сделать , но мне нужен только id

2023-06-22 07:05 UTC, Rorshix commented on pom.xml
> +		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
Маневр был в том что я добавлял wrapper , и потом перекинул все обратно

2023-06-22 07:05 UTC, Rorshix commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +				new ReviewNotFoundException(String.format("Attempt to get review with absent id = %d",
Исправлю

2023-06-22 10:33 UTC, mrmaximum80 commented
1. Нужно добиться проходения тестов.
2. Я бы просто закрыл данный ПР без мерджа от греха. Лучше влить к себе все изменения с гитхаба, и сделать реквест еще раз.

2023-06-22 11:01 UTC, closed without merging

2023-06-22 11:29 UTC, Rorshix commented on pom.xml
> +		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
Исправлено